### ISSUE TITLE
Pure virtual method called

### ISSUE THREAD

**Issue by mklingen** [personalrobotics/dart-examples#1]
Not sure what would be causing this, but this is what's happening when I try to run this example

output from gdb:
```
pure virtual method called
terminate called without an active exception

Program received signal SIGABRT, Aborted.
0x00007ffff4e98cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff4e98cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff4e9c0d8 in __GI_abort () at abort.c:89
#2  0x00007ffff57a3535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff57a16d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff57a1703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff57a21bf in __cxa_pure_virtual () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff6e0c291 in dart::utils::DartLoader::readFileToString(std::shared_ptr<dart::common::ResourceRetriever> const&, dart::common::Uri const&, std::string&) () from /usr/local/lib/libdart.so.5.1
#7  0x00007ffff6e115b6 in dart::utils::DartLoader::parseSkeleton(dart::common::Uri const&, std::shared_ptr<dart::common::ResourceRetriever> const&) ()
   from /usr/local/lib/libdart.so.5.1
#8  0x0000000000406bfa in main ()
```

**Comment by mklingen** [comment]
this is the only code I'm using

```
    const std::shared_ptr<r3::util::CatkinResourceRetriever> resourceRetriever = std::make_shared<r3::util::CatkinResourceRetriever>();

    dart::utils::DartLoader urdfLoader;
    const dart::dynamics::SkeletonPtr skeleton= urdfLoader.parseSkeleton("package://herb_description/robots/herb.urdf", resourceRetriever);
```

**Comment by mklingen** [comment]
this was caused by a linking error on my part
